version: '3.1'
services:
  backend-api:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    volumes:
      - './backend:/opt/app'
    restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: weather
      MYSQL_DATABASE: weather_db
    ports:
    - '3306:3306'
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql